---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: trailing-whitespace

  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.7.7
    hooks:
      - id: actionlint-docker

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint-docker

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.15
    hooks:
      - id: trufflehog
