name: Check Production
on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  get_previous_status:
    runs-on: ubuntu-latest
    outputs:
      previous_status: ${{ steps.get_previous_status.outputs.status }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Get Previous Run Status
        id: get_previous_status
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              per_page: 2,
              page: 1,
            });
            return runs[1].status;

  run-tests:
    needs: get_previous_status
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    with:
      test-environment: production
      ref: ${{ github.sha }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{always() && needs.get_previous_status.outputs.previous_status != 'success' && needs.run-tests.result != 'success'}}
    needs:
      - get_previous_status
      - run-tests
    steps:
      - uses: actions/checkout@v4
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: GitHub
          SLACK_TITLE: Workflow ${{ needs.run-tests.result }}
          SLACK_CHANNEL: production-alerts
          SLACK_COLOR: failure
          MSG_MINIMAL: actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
