name: Check Production
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-tests:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    with:
      test-url: "https://www.trade-tariff.service.gov.uk"
      ref: ${{ github.sha }}
