name: development
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - run: pip install pre-commit
      - run: pre-commit run --all-files
  run-tests:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    with:
      test-url: "https://dev.trade-tariff.service.gov.uk"
      ref: ${{ github.sha }}
